# -*- coding: utf-8 -*-
"""problema 2 centroide de un triangulo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IPUwjlrJuB0gRd2PlAplDmhzZO4ktLCZ
"""

#centroide de un triangulo (problema 3)
import sympy as sp

# Demostración analítica
a_x, a_y, a_z = sp.symbols('a_x a_y a_z')
b_x, b_y, b_z = sp.symbols('b_x b_y b_z')
c_x, c_y, c_z = sp.symbols('c_x c_y c_z')

a = sp.Matrix([a_x, a_y, a_z])
b = sp.Matrix([b_x, b_y, b_z])
c = sp.Matrix([c_x, c_y, c_z])

# Punto medio de AB
m_ab = (a + b) / 2

# Centroide (2/3 del camino desde C hasta M_AB)
g = c + (m_ab - c) * sp.Rational(2, 3)
g_simplified = sp.simplify(g)

# Fórmula directa
g_direct = (a + b + c) / 3

# Verificación
verification = sp.simplify(g_simplified - g_direct)

# Ejemplo numérico
a_num = sp.Matrix([0, 0, 0])
b_num = sp.Matrix([4, 0, 0])
c_num = sp.Matrix([0, 3, 0])
g_num = (a_num + b_num + c_num) / 3

# Resultados
print("*** Demostración del vector posición del centroide ***")
print("\nFórmula obtenida geométricamente:")
sp.pprint(g_simplified)
print("\nFórmula directa:")
sp.pprint(g_direct)
print("\nVerificación (debe ser vector cero):")
sp.pprint(verification)
print("\nEjemplo numérico (triángulo rectángulo en (0,0), (4,0), (0,3)):")
print("Centroide calculado:", g_num)